select * from customer_shopping_behavior limit 5;
USE customer;
SHOW TABLES;
-- Q1 what is the total revenue generated by male vs. female customers
select  
gender ,sum(purchase_amount) as revenue from customer_shopping_behavior
group by gender;
-- Q2 which customers used the discount but still spent more than the avg. purchase amount ?
SELECT customer_id,
       AVG(purchase_amount) AS avg_amount
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
GROUP BY customer_id
HAVING AVG(purchase_amount) >
       (SELECT AVG(purchase_amount)
        FROM customer_shopping_behavior);

-- Q3 which are the top 5 products with the highest avg. review rating?
select item_purchased , avg(review_rating) as avg_rating from customer_shopping_behavior
group by item_purchased  
order by avg_rating DESC 
LIMIT 5;
-- Q4 compare the avg. Purchase amounts b/w Standard and Express shipping 
select shipping_type , avg(purchase_amount) avg_purchase_amount from customer_shopping_behavior
where shipping_type IN ('Standard','Express')
group by shipping_type;
-- Q5 do subscribed customers spend more? compare avg spend and total revenue b/w subscribed and non-subscribers 
select subscription_status , count(customer_id),round(avg(purchase_amount),2) as AVG_spend ,round(sum(purchase_amount),2)as revenue from customer_shopping_behavior 
group by 1
order by  AVG_spend , revenue DESC ;
-- Q6 which 5 products have the highest percantage of purchases with discount applied?
select item_purchased ,  ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS discount_purchase_percentage from customer_shopping_behavior 
group by 1
order by 2 DESC
limit 5;
--

-- Q7 segment customers into new , returning , and loyal based on their based total 
-- number of previous purchases , and show the count of each segment..
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behavior
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q8 what are the top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;
-- Q9 are customer who are repeat buyers (more than 5 previous purchases) also likely to subscrib?
SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Other Customers'
    END AS customer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers,
    ROUND(
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS subscription_rate
FROM customer_shopping_behavior
GROUP BY customer_type;
-- Q10 what is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 /
        (SELECT SUM(purchase_amount)
         FROM customer_shopping_behavior),
        2
    ) AS revenue_contribution_percentage
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY revenue DESC;

